export const data = [
  {
    currency: "USD",
    department: "Engineering",
    name: "Abhishek",
    salary: "145000",
    sub_department: "Platform",
  },
  {
    currency: "USD",
    department: "Banking",
    name: "Anurag",
    on_contract: "true",
    salary: "90000",
    sub_department: "Loan",
  },
  {
    currency: "USD",
    department: "Engineering",
    name: "Himani",
    salary: "240000",
    sub_department: "Platform",
  },
  {
    currency: "USD",
    department: "Operations",
    name: "Yatendra",
    salary: "30",
    sub_department: "CustomerOnboarding",
  },
  {
    currency: "USD",
    department: "Engineering",
    name: "Ragini",
    salary: "30",
    sub_department: "Platform",
  },
  {
    currency: "USD",
    department: "Engineering",
    name: "Nikhil",
    on_contract: "true",
    salary: "110000",
    sub_department: "Platform",
  },
  {
    currency: "USD",
    department: "Administration",
    name: "Guljit",
    salary: "30",
    sub_department: "Agriculture",
  },
  {
    currency: "EUR",
    department: "Operations",
    name: "Himanshu",
    salary: "70000",
    sub_department: "CustomerOnboarding",
  },
  {
    currency: "INR",
    department: "Engineering",
    name: "Anupam",
    salary: "200000000",
    sub_department: "Platform",
  },
];
